# Generated by Django 5.2.4 on 2026-01-08 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_alter_client_id_alter_customuser_id_alter_work_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='work_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='MyApp.work')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkUpload',
        ),
    ]
