# Generated by Django 6.0.3 on 2026-03-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_alter_client_options_alter_work_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Project', max_length=255)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('site_description', models.TextField(blank=True, default='Professional web design and development services')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('allow_client_registration', models.BooleanField(default=True)),
                ('show_testimonials', models.BooleanField(default=True)),
                ('show_portfolio', models.BooleanField(default=True)),
                ('maintenance_message', models.TextField(blank=True, default='We are currently under maintenance. Please check back soon!')),
                ('welcome_message', models.TextField(blank=True, default='Welcome to our platform')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Website Settings',
            },
        ),
        migrations.RemoveField(
            model_name='work',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='workfile',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='workfile',
            name='work',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={},
        ),
        migrations.RemoveField(
            model_name='client',
            name='company',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password_changed',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='work',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='work',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='WorkFile',
        ),
    ]
