# Generated by Django 6.0.3 on 2026-03-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_websitesettings_remove_work_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
