# Generated by Django 6.0.3 on 2026-03-31 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
    ]
