# Generated by Django 6.0.3 on 2026-04-08 05:25

import MyApp.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def seed_default_company_and_scope_data(apps, schema_editor):
    CustomUser = apps.get_model("MyApp", "CustomUser")
    Company = apps.get_model("MyApp", "Company")
    Client = apps.get_model("MyApp", "Client")
    Staff = apps.get_model("MyApp", "Staff")
    Work = apps.get_model("MyApp", "Work")
    Notification = apps.get_model("MyApp", "Notification")
    DeletionRequest = apps.get_model("MyApp", "DeletionRequest")
    SubscriptionPaymentRequest = apps.get_model("MyApp", "SubscriptionPaymentRequest")

    owner = CustomUser.objects.filter(is_superuser=True).order_by("id").first()
    if owner is None:
        owner = CustomUser.objects.order_by("id").first()
    if owner is None:
        owner = CustomUser.objects.create(username="platform_owner", is_superuser=True, is_staff=True, is_active=True)
        owner.password = make_password("change-me-please")
        owner.save(update_fields=["password"])

    company, _ = Company.objects.get_or_create(
        code="default-company",
        defaults={
            "name": "Default Company",
            "owner_user_id": owner.id,
            "business_email": "",
            "business_phone": "",
            "plan_status": "trial",
            "is_active": True,
        },
    )

    # Assign tenant to existing rows.
    Client.objects.filter(company__isnull=True).update(company=company)
    Staff.objects.filter(company__isnull=True).update(company=company)
    Work.objects.filter(company__isnull=True).update(company=company)
    Notification.objects.filter(company__isnull=True).update(company=company)
    DeletionRequest.objects.filter(company__isnull=True).update(company=company)

    # Map old payment requests (client-owned) to the same company.
    for payment in SubscriptionPaymentRequest.objects.filter(company__isnull=True).select_related("client"):
        if payment.client_id:
            payment.company_id = payment.client.company_id or company.id
        else:
            payment.company_id = company.id
        payment.save(update_fields=["company"])

    clients = Client.objects.filter(company=company)
    if clients.exists():
        first_client = clients.order_by("id").first()
        trial_start = first_client.trial_started_at
        trial_end = max([c.trial_ends_at for c in clients if c.trial_ends_at], default=first_client.trial_ends_at)
        paid_until = max(
            [c.subscription_expires_at for c in clients if c.subscription_expires_at],
            default=None,
        )
        company.trial_started_at = trial_start
        company.trial_ends_at = trial_end
        company.plan_expires_at = paid_until
        now = django.utils.timezone.now()
        if paid_until and paid_until > now:
            company.plan_status = "active"
        elif trial_end and trial_end > now:
            company.plan_status = "trial"
        else:
            company.plan_status = "expired"
        company.save(update_fields=["trial_started_at", "trial_ends_at", "plan_expires_at", "plan_status"])


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0016_client_business_email_client_business_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('business_email', models.EmailField(blank=True, default='', max_length=254)),
                ('business_phone', models.CharField(blank=True, default='', max_length=20)),
                ('trial_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trial_ends_at', models.DateTimeField(default=MyApp.models.default_trial_end)),
                ('plan_status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired')], default='trial', max_length=20)),
                ('plan_expires_at', models.DateTimeField(blank=True, null=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=MyApp.models.default_plan_price, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='MyApp.company'),
        ),
        migrations.AddField(
            model_name='deletionrequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to='MyApp.company'),
        ),
        migrations.AddField(
            model_name='notification',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='MyApp.company'),
        ),
        migrations.AddField(
            model_name='staff',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='MyApp.company'),
        ),
        migrations.AddField(
            model_name='subscriptionpaymentrequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='MyApp.company'),
        ),
        migrations.AddField(
            model_name='work',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='MyApp.company'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('company', 'client_id')},
        ),
        migrations.RunPython(seed_default_company_and_scope_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='subscriptionpaymentrequest',
            name='client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='monthly_price',
        ),
        migrations.RemoveField(
            model_name='client',
            name='subscription_expires_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='subscription_status',
        ),
        migrations.RemoveField(
            model_name='client',
            name='trial_ends_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='trial_started_at',
        ),
    ]
