# Generated by Django 6.0.3 on 2026-04-08 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0017_remove_subscriptionpaymentrequest_client_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Company', max_length=255)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='company_settings/')),
                ('site_description', models.TextField(blank=True, default='Company workspace settings')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('allow_client_registration', models.BooleanField(default=True)),
                ('show_testimonials', models.BooleanField(default=True)),
                ('show_portfolio', models.BooleanField(default=True)),
                ('maintenance_message', models.TextField(blank=True, default='We are currently under maintenance. Please check back soon!')),
                ('welcome_message', models.TextField(blank=True, default='Welcome to our platform')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='MyApp.company')),
            ],
            options={
                'verbose_name_plural': 'Company Settings',
            },
        ),
    ]
