# Generated by Django 6.0.3 on 2026-07-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0022_subscriptionpaymentrequest_selected_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletionrequest',
            name='target_type',
            field=models.CharField(choices=[('client', 'Client'), ('work', 'Work'), ('staff', 'Staff'), ('client_deactivate', 'Client Deactivation'), ('client_activate', 'Client Activation')], max_length=20),
        ),
    ]
