# Generated by Django 6.0.3 on 2026-08-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0023_alter_deletionrequest_target_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
