# Generated by Django 6.0.3 on 2026-08-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0024_company_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='base_plan_price',
            field=models.DecimalField(decimal_places=2, default=999.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='enterprise_plan_price',
            field=models.DecimalField(decimal_places=2, default=29999.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='free_plan_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='premium_plan_price',
            field=models.DecimalField(decimal_places=2, default=9999.0, max_digits=10),
        ),
    ]
